name: ok_http_dart
description: A easy to use http wrapper made for personal usage.
homepage: "https://github.com/Noobware1/ok_http"
repository: "https://github.com/Noobware1/ok_http"
version: 1.1.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.6 <4.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  html: ^0.15.4
  http: ^0.13.6
